apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
  namespace: argocd
spec:
  destination:
    namespace: sample-namespace
    server: https://kubernetes.default.svc
  project: default
  source:
    path: .
    repoURL: https://github.com/your-repo/sample-app
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      annotations:
        environment: production
        linkerd.io/inject: enabled
      labels:
        app: myapp
        hello: world
        tier: backend1
